name: base
channels:
  - conda-forge
dependencies:
  - bibtexparser
  - cerberus
  - corner
  - dask>=2
  - distributed>=2
  - emcee<3
  - numpy
  - pycalphad>=0.8.4
  - pyyaml
  - scikit-learn
  - scipy
  - sympy>=1.5.1
  - tinydb>=4
